- src/bundle/Resources/config/views.yaml
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1694](https://issues.ibexa.co/browse/IBX-1694)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#12
In this Pull Request we rename Ibexa's dependency injection container service tags according to the map provided by ibexa/compatibility-layer#12 as a part of the rebranding process. Backward compatibility for old service tags is provided by ibexa/compatibility-layer#12.
> IBX-1694: Rebranded dependency injection container service tags

- src/bundle/Resources/config/default_settings.yaml
- src/bundle/Resources/config/forms.yaml
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-1696](https://issues.ibexa.co/browse/IBX-1696)
| **Type**                                   | feature
| **Target Ibexa version** | `v4.0`
| **BC breaks**                          | yes, requires ibexa/compatibility-layer#31
Rebranded service container parameter names and Ibexa Config Resolver namespaces to follow unified pattern
> IBX-1696: Rebranded Container parameters and Config Resolver namespaces

- src/bundle/Form/Type/SearchType.php
- src/bundle/Resources/translations/search.en.xliff
| Tickets       |  https://issues.ibexa.co/browse/IBX-5697
| Bug fix?      | no
With https://github.com/ibexa/admin-ui/pull/780
> IBX-5697: [Dropdown] Change default placeholder to "All"

- composer.json
| Tickets       |  N/A
Aligned composer fix-cs script with repository template in order to avoid
```
[PhpCsFixer\ConfigurationException\InvalidConfigurationException (16)]        
The progress type "estimating" is not defined, supported are "none", "dots".  
```
error.
> Fixed composer fix-cs script definition

- src/lib/QueryType/SearchQueryType.php
| Tickets       |  N/A
| Bug fix?      | no
| Tests pass?   | yes/no
`SearchService` contract should be used as constructor argument instead of implementation.
> Fixed importing SearchService contract in SearchQueryType

- src/bundle/Form/Type/SearchType.php
- src/bundle/Form/Type/SortingDefinitionChoiceType.php
- src/bundle/Resources/config/forms.yaml
- src/bundle/Resources/config/sorting_definitions.yaml
- src/bundle/Resources/translations/ibexa_search.en.xliff
- src/contracts/SortingDefinition/SortingDefinitionProviderInterface.php
- src/lib/SortingDefinition/Provider/DateSortingDefinitionProvider.php
- src/lib/SortingDefinition/Provider/NameSortingDefinitionProvider.php
- src/lib/SortingDefinition/Provider/RelevanceSortingDefinitionProvider.php
- src/lib/SortingDefinition/SortingDefinitionRegistry.php
- tests/lib/SortingDefinition/Provider/NameSortingDefinitionProviderTest.php
- tests/lib/SortingDefinition/Provider/RelevanceSortingDefinitionProviderTest.php
- tests/lib/SortingDefinition/SortingDefinitionRegistryTest.php
| Tickets       |  [IBX-6338](https://issues.ibexa.co/browse/IBX-6338)
| Bug fix?      | no
| BC breaks?    | yes
| Tests pass?   | yes/no
Fix typo from #25
- on several classnames
- on a function name
- in translation namespace `ibexa_search` on a `sort_definition` family member.
> IBX-6338: Fix typo In sort definition

- src/bundle/DependencyInjection/Configuration/Parser/SiteAccessAware/SuggestionParser.php
- src/bundle/Resources/translations/ibexa_search.en.xliff
| Tickets       |  N/A
Fixes:
```
In AnnotationException.php line 40:
[Semantical Error] The annotation "@Example" in class Ibexa\Bundle\Search\DependencyInjection\Configuration\Parser\SiteAccessAware\SuggestionParser was   
never imported. Did you maybe forget to add a "use" statement for this annotation?  
```
> Fixed translation extraction

- src/lib/QueryType/SearchQueryType.php
- src/lib/View/SearchViewBuilder.php
| Question                 | Answer                                              |
|--------------------------|-----------------------------------------------------|
| **JIRA issue**           | [IBX-6649](https://issues.ibexa.co/browse/IBX-6649) |
| **Type**                 | feature                                             |
| **Target Ibexa version** | `v4.6`                                              |
| **BC breaks**            | no                                                  |
Depends on https://github.com/ibexa/core/pull/276 Needed for https://github.com/ibexa/admin-ui/pull/923
> IBX-6649: Added support for spell checking

- src/bundle/Controller/SuggestionController.php
- src/lib/EventDispatcher/EventListener/ContentSuggestionSubscriber.php
- src/lib/View/SearchViewFilter.php
| Tickets       |  [IBX-7236](https://issues.ibexa.co/browse/IBX-7236) 
This PR fixes:
- an issue with min_query_lenght settings
- an issue with finding only entire words
- related PR https://github.com/ibexa/core/pull/298
> IBX-7236: Suggestions only work with entire words

- src/bundle/Resources/config/services/normalizers.yaml
- src/contracts/Model/Suggestion/SuggestionCollection.php
- src/lib/EventDispatcher/EventListener/ContentSuggestionSubscriber.php
- src/lib/Serializer/Normalizer/Suggestion/SuggestionCollectionNormalizer.php
- tests/lib/Serializer/Normalizer/Suggestion/SuggestionCollectionNormalizerTest.php
| Tickets       |  [IBX-7419](https://issues.ibexa.co/browse/IBX-7419) 
| Bug fix?      | no
| New feature?  | yes
| Doc needed?   | yes
This PR adds new two properties in the suggestion endpoint, `suggestionResults` and `totalCount`.
`http://127.0.0.1:8000/suggestion?query=ala&limit=1`
```json
{
"suggestionResults": [
{
"contentId": 66,
"locationId": 67,
"contentTypeIdentifier": "article",
"name": "abra ala kadabra",
"pathString": "2/67",
"type": "content",
"parentLocations": [
{
"id": 52,
"locationId": 2,
"name": "Ibexa Digital Experience Platform"
},
{ "id": 66, "locationId": 67, "name": "abra ala kadabra" }
]
}
], …
```
> IBX-7419: [autcomplete] Add the total number of results to the autocomplete/suggestions endpoint

- src/contracts/Model/Suggestion/SuggestionCollection.php
- src/lib/EventDispatcher/EventListener/ContentSuggestionSubscriber.php
- tests/lib/EventDispatcher/EventListener/ContentSuggestionSubscriberTest.php
| Tickets       |  [IBX-7361](https://issues.ibexa.co/browse/IBX-7361) 
This PR fixes sorting issues
> IBX-7361: The search criterion is searching for all text fields of contents

- src/lib/EventDispatcher/EventListener/ContentSuggestionSubscriber.php
| Tickets       |  [IBX-7512](https://issues.ibexa.co/browse/IBX-7512) 
> IBX-7512: Removed searching by partial words

- src/lib/Mapper/SearchHitToContentSuggestionMapper.php
- tests/lib/Mapper/SearchHitToContentSuggestionMapperTest.php
| Tickets       |  [IBX-7462](https://issues.ibexa.co/browse/IBX-7462) 
> IBX-7462: Removed "Top Level Nodes" from breadcrumbs in search suggestions

- .github/workflows/ci.yaml
- composer.json
- src/lib/Mapper/PagerSearchContentToDataMapper.php
| :ticket: Issue | IBX-8119 |
| Blocks | CI of #46 |
Seems there was never a PR created from this branch. Bumping PHP to 8.3
It includes:
- changing `composer.json` requirements
- sorting `composer.json` packages
- updating GHA CI jobs config
- fixing issue with iterables used as arrays which is recently reported by PHPStan. This time fix is simple so I've applied it right away instead of adding the issue to the baseline.
> IBX-8119: Upgraded minimum PHP version to 8.3

- composer.json
- src/bundle/Controller/SearchController.php
- src/bundle/DependencyInjection/Configuration/Parser/Search.php
- src/bundle/DependencyInjection/Configuration/Parser/SearchView.php
- src/bundle/DependencyInjection/IbexaSearchExtension.php
- src/bundle/Form/ChoiceLoader/ConfiguredLanguagesChoiceLoader.php
- src/bundle/Form/ChoiceLoader/ContentTypeChoiceLoader.php
- src/bundle/Form/Data/SearchData.php
- src/bundle/Form/Data/SearchUsersData.php
- src/bundle/Form/DataTransformer/DateIntervalTransformer.php
- src/bundle/Form/DataTransformer/UserTransformer.php
- src/bundle/Form/DataTransformer/UsersTransformer.php
- src/bundle/Form/Type/ContentTypeChoiceType.php
- src/bundle/Form/Type/DateIntervalType.php
- src/bundle/Form/Type/LanguageChoiceType.php
- src/bundle/Form/Type/SearchType.php
- src/bundle/Form/Type/SearchUsersType.php
- src/bundle/Form/Type/SectionChoiceType.php
- src/bundle/Form/Type/UserType.php
- src/bundle/IbexaSearchBundle.php
- src/lib/Mapper/PagerSearchContentToDataMapper.php
- src/lib/QueryType/SearchQueryType.php
- src/lib/View/SearchView.php
- src/lib/View/SearchViewBuilder.php
- src/lib/View/SearchViewFilter.php
- src/lib/View/SearchViewProvider.php
| :ticket: Issue | IBX-8139 |
Dropped `class_alias` BC layer statements from all classes using https://github.com/ibexa/rector/pull/2
No QA needed
Document that our BC layer has been dropped
> IBX-8139: Dropped class_alias BC layer statements from all classes

- src/lib/SortingDefinition/Provider/NameSortingDefinitionProvider.php
- tests/lib/EventDispatcher/EventListener/ContentSuggestionSubscriberTest.php
- tests/lib/SortingDefinition/Provider/NameSortingDefinitionProviderTest.php
| :ticket: Issue | IBX-8394 |
Replaced usages of `\Ibexa\Bundle\Core\ApiLoader\RepositoryConfigurationProvider`
with `\Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface`, using ibexa/rector#6.
No QA needed. Regression tests should be enough.
This is code refactoring without behavior change. No documentation changes needed.
> IBX-8394: Used new RepositoryConfigurationProviderInterface contract

- phpstan-baseline.neon
- src/lib/Mapper/PagerSearchContentToDataMapper.php
| :ticket: Issue | N/A |
Fixed issues reported by phpstan. See https://github.com/ibexa/search/actions/runs/12271834106/job/34239401197?pr=51 
N/A
N/A
> Fixed issues reported by phpstan

- composer.json
- phpstan-baseline.neon
- src/bundle/DependencyInjection/Configuration/Parser/Search.php
- src/bundle/DependencyInjection/Configuration/Parser/SearchView.php
- src/bundle/DependencyInjection/IbexaSearchExtension.php
- src/bundle/Form/ChoiceLoader/ConfiguredLanguagesChoiceLoader.php
- src/bundle/Form/ChoiceLoader/ContentTypeChoiceLoader.php
- src/bundle/IbexaSearchBundle.php
- src/bundle/Twig/Extension/SearchFacetsExtension.php
- tests/lib/EventDispatcher/EventListener/ContentSuggestionSubscriberTest.php
- tests/lib/QueryType/SearchQueryTypeTest.php
- tests/lib/Service/Event/SuggestionServiceTest.php
- tests/lib/SortingDefinition/Provider/NameSortingDefinitionProviderTest.php
> [!CAUTION]
> This is a part of bigger set of changes, to be merged together when ready
> - [x] :exclamation:  **Remove TMP commits before merge** :exclamation:
| :ticket: Issue | IBX-8470 |
- https://github.com/ibexa/core/pull/447
- https://github.com/ibexa/doctrine-schema/pull/27
This PR bumps Symfony to v6 with codebase upgrades.
Key changes:
Sanities in the form of regression tests.
No documentation required.
> IBX-8470: Upgraded codebase to Symfony 6

- .github/workflows/ci.yaml
- composer.json
- phpstan-baseline.neon
- rector.php
- src/bundle/Form/Type/ContentTypeChoiceType.php
- src/bundle/Form/Type/DateIntervalType.php
- src/bundle/Form/Type/SearchType.php
- src/bundle/Form/Type/SearchUsersType.php
- src/bundle/Form/Type/SectionChoiceType.php
- src/bundle/Form/Type/UserType.php
- src/bundle/Resources/config/services/suggestions.yaml
- src/bundle/ValueResolver/SuggestionQueryArgumentResolver.php
| :ticket: Issue | IBX-9584  |
Enabled and executed automatic refactoring rules defined for Symfony 6.x.
* [Form] Removed redundant PHPDocs
* [Form] Added missing return type declarations
* [HTTP] Migrated from ArgumentValueResolvedInterface to ValueResolverInterfaceInterface
Additionally added rector job to CI setup to prevent merging up code which is not compatible with Symfony 6+.
Sanities.
N/A
> IBX-9584: Resolved Symfony 6.x deprecations

- phpstan-baseline.neon
- src/bundle/Form/ChoiceLoader/ContentTypeChoiceLoader.php
- src/bundle/Form/Data/SearchData.php
- src/bundle/Form/Data/SearchUsersData.php
- src/bundle/Form/DataTransformer/UserTransformer.php
- src/bundle/Form/DataTransformer/UsersTransformer.php
- src/bundle/Form/Type/ContentTypeChoiceType.php
- src/bundle/Form/Type/LanguageChoiceType.php
- src/bundle/Form/Type/SearchType.php
- src/bundle/Form/Type/SearchUsersType.php
- src/bundle/Form/Type/SectionChoiceType.php
- src/bundle/Form/Type/UserType.php
- src/lib/Mapper/PagerSearchContentToDataMapper.php
- src/lib/View/SearchViewBuilder.php
- src/lib/View/SearchViewFilter.php
- src/lib/View/SearchViewProvider.php
- tests/lib/Service/Event/SuggestionServiceTest.php
> [!CAUTION]
> These changes are volatile and - in some repositories - extensive, so they need to be carefully reviewed before merging.
| :ticket: Issue | IBX-9727 |
Added missing strict type hints using `\Rector\Set\ValueObject\SetList::TYPE_DECLARATION` set.
Additionally FQCNs have been imported for every affected file using PHP CS Fixer, in some cases they might override unrelated lines.
Regression tests.
> IBX-9727: Added missing type hints

- composer.json
- phpstan-baseline.neon
- src/bundle/Form/DataTransformer/DateIntervalTransformer.php
- src/bundle/Form/DataTransformer/UserTransformer.php
- src/bundle/Form/DataTransformer/UsersTransformer.php
- src/bundle/Twig/Extension/SearchFacetsExtension.php
- src/lib/Serializer/Normalizer/Suggestion/ContentSuggestionNormalizer.php
- src/lib/Serializer/Normalizer/Suggestion/LocationNormalizer.php
- src/lib/Serializer/Normalizer/Suggestion/ParentLocationCollectionNormalizer.php
- src/lib/Serializer/Normalizer/Suggestion/SuggestionCollectionNormalizer.php
> [!CAUTION]
> # Merge together with other IBX-8471 Pull Requests
> - [ ] Make sure TMP commit(s) are dropped before merging
| :ticket: Issue | IBX-8471 |
Upgrading Symfony dependencies to version 7 along with necessary 3rd party packages and codebase changes.
Key changes:
Sanity tests and/or regression builds.
> IBX-8471: Upgraded codebase to Symfony 7

- rector.php
- src/bundle/DependencyInjection/IbexaSearchExtension.php
| :ticket: Issue | IBX-9968  |
Enabled Rector Symfony 7.0, 7.1 and 7.2 sets. Resolved the following deprecations:
```
* [symfony/http-kernel] Replaced usage of internal Symfony\Component\HttpKernel\DependencyInjection\Extension class
```
Sanities.
> IBX-9968: Resolved Symfony 7.x deprecations

- phpstan-baseline.neon
- src/bundle/Resources/config/services.yaml
- src/bundle/Resources/config/views.yaml
- src/contracts/Mapper/PagerSearchDataMapper.php
- src/lib/Mapper/PagerSearchContentToDataMapper.php
- src/lib/View/SearchViewBuilder.php
| :ticket: Issue | EZP-31745 /  https://issues.ibexa.co/browse/IBX-10053 |
- https://github.com/ezsystems/ezplatform-search/pull/7
Just basic sanities on admin ui search. This should change absolutly nothing in terms of functionality.
> IBX-10053: Introduced PagerSearchDataMapper interface

- src/bundle/DependencyInjection/IbexaSearchExtension.php
- src/bundle/Twig/Extension/SearchFacetsExtension.php
| :ticket: Issue | N/A |
```
In StringTypeResolver.php line 88:
[Symfony\Component\TypeInfo\Exception\UnsupportedException]  
Cannot resolve "array<(ChoiceGroupView | ChoiceView)>".      
Exception trace:
at /home/awojs/ibexa/ibexa-dxp-on-sf73/vendor/symfony/type-info/TypeResolver/StringTypeResolver.php:88
Symfony\Component\TypeInfo\TypeResolver\StringTypeResolver->resolve() at /home/awojs/ibexa/ibexa-dxp-on-sf73/vendor/symfony/property-info/Extractor/PhpStanExtractor.php:254
Symfony\Component\PropertyInfo\Extractor\PhpStanExtractor->getTypeFromConstructor() at /home/awojs/ibexa/ibexa-dxp-on-sf73/vendor/symfony/property-info/Extractor/ConstructorExtractor.php:35
Symfony\Component\PropertyInfo\Extractor\ConstructorExtractor->getType() at …
```
> [Translations] Fixed translation extraction
